config/routes.rb
Rails.application.routes.draw do
  resources :bath_reminders
  resources :baths
  resources :vermifuge_reminders
  resources :vermifuges
  resources :appointment_reminders
  resources :appointments
  resources :vaccines
  resources :weights
  resources :pets
  resources :owners
  resources :bath_reminders
  resources :baths
  resources :bath_reminders
  resources :baths
  resources :bath_reminders
  resources :baths
  resources :vermifuge_reminders
  resources :vermifuges
  resources :vermifuge_reminders
  resources :vermifuges
  resources :vermifuge_reminders
  resources :vermifuges
  resources :vermifuge_reminders
  resources :appointment_reminders
  resources :appointments
  resources :owners
  resources :vaccines
  resources :vaccines
  resources :vaccines
  resources :weights
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'home/index'

  root 'home#index'

  resources :pets

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :pet
end

app/models/appointment_reminder.rb
class AppointmentReminder < ActiveRecord::Base
  belongs_to :appointment
end

app/models/bath.rb
class Bath < ActiveRecord::Base
end

app/models/bath_reminder.rb
class BathReminder < ActiveRecord::Base
  belongs_to :bath
end

app/models/owner.rb
class Owner < ActiveRecord::Base
end

app/models/pet.rb
class Pet < ActiveRecord::Base
  belongs_to :owner
end

app/models/vaccine.rb
class Vaccine < ActiveRecord::Base
  belongs_to :pet
end

app/models/vermifuge.rb
class Vermifuge < ActiveRecord::Base
end

app/models/vermifuge_reminder.rb
class VermifugeReminder < ActiveRecord::Base
  belongs_to :vermifuge
end

app/models/weight.rb
class Weight < ActiveRecord::Base
  belongs_to :pet
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:owner_id, :name, :birth, :sex, :specie, :breed, :color, :image)
    end
end

app/controllers/vermifuges_controller.rb
class VermifugesController < ApplicationController
  before_action :set_vermifuge, only: [:show, :edit, :update, :destroy]

  # GET /vermifuges
  # GET /vermifuges.json
  def index
    @vermifuges = Vermifuge.all
  end

  # GET /vermifuges/1
  # GET /vermifuges/1.json
  def show
  end

  # GET /vermifuges/new
  def new
    @vermifuge = Vermifuge.new
  end

  # GET /vermifuges/1/edit
  def edit
  end

  # POST /vermifuges
  # POST /vermifuges.json
  def create
    @vermifuge = Vermifuge.new(vermifuge_params)

    respond_to do |format|
      if @vermifuge.save
        format.html { redirect_to @vermifuge, notice: 'Vermifuge was successfully created.' }
        format.json { render :show, status: :created, location: @vermifuge }
      else
        format.html { render :new }
        format.json { render json: @vermifuge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vermifuges/1
  # PATCH/PUT /vermifuges/1.json
  def update
    respond_to do |format|
      if @vermifuge.update(vermifuge_params)
        format.html { redirect_to @vermifuge, notice: 'Vermifuge was successfully updated.' }
        format.json { render :show, status: :ok, location: @vermifuge }
      else
        format.html { render :edit }
        format.json { render json: @vermifuge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vermifuges/1
  # DELETE /vermifuges/1.json
  def destroy
    @vermifuge.destroy
    respond_to do |format|
      format.html { redirect_to vermifuges_url, notice: 'Vermifuge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vermifuge
      @vermifuge = Vermifuge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vermifuge_params
      params.require(:vermifuge).permit(:title, :manufacturer_name, :date, :dose, :notes, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/baths_helper.rb
module BathsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/vaccines_helper.rb
module VaccinesHelper
end

app/helpers/vermifuges_helper.rb
module VermifugesHelper
end

app/helpers/weights_helper.rb
module WeightsHelper
end

app/views/vermifuges/_form.html.erb
<%= form_for(@vermifuge) do |f| %>
  <% if @vermifuge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vermifuge.errors.count, "error") %> prohibited this vermifuge from being saved:</h2>

      <ul>
      <% @vermifuge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :manufacturer_name %><br>
    <%= f.text_field :manufacturer_name %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :dose %><br>
    <%= f.text_field :dose %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vermifuges/edit.html.erb
<h1>Editing Vermifuge</h1>

<%= render 'form' %>

<%= link_to 'Show', @vermifuge %> |
<%= link_to 'Back', vermifuges_path %>

app/views/vermifuges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Vermifuges</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Manufacturer name</th>
      <th>Date</th>
      <th>Dose</th>
      <th>Notes</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vermifuges.each do |vermifuge| %>
      <tr>
        <td><%= vermifuge.title %></td>
        <td><%= vermifuge.manufacturer_name %></td>
        <td><%= vermifuge.date %></td>
        <td><%= vermifuge.dose %></td>
        <td><%= vermifuge.notes %></td>
        <td><%= vermifuge.image %></td>
        <td><%= link_to 'Show', vermifuge %></td>
        <td><%= link_to 'Edit', edit_vermifuge_path(vermifuge) %></td>
        <td><%= link_to 'Destroy', vermifuge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vermifuge', new_vermifuge_path %>

app/views/vermifuges/new.html.erb
<h1>New Vermifuge</h1>

<%= render 'form' %>

<%= link_to 'Back', vermifuges_path %>

app/views/vermifuges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @vermifuge.title %>
</p>

<p>
  <strong>Manufacturer name:</strong>
  <%= @vermifuge.manufacturer_name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @vermifuge.date %>
</p>

<p>
  <strong>Dose:</strong>
  <%= @vermifuge.dose %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @vermifuge.notes %>
</p>

<p>
  <strong>Image:</strong>
  <%= @vermifuge.image %>
</p>

<%= link_to 'Edit', edit_vermifuge_path(@vermifuge) %> |
<%= link_to 'Back', vermifuges_path %>