config/routes.rb
Rails.application.routes.draw do
  resources :bath_reminders
  resources :baths
  resources :vermifuge_reminders
  resources :vermifuges
  resources :appointment_reminders
  resources :appointments
  resources :vaccines
  resources :weights
  resources :pets
  resources :owners
  resources :bath_reminders
  resources :baths
  resources :bath_reminders
  resources :baths
  resources :bath_reminders
  resources :baths
  resources :vermifuge_reminders
  resources :vermifuges
  resources :vermifuge_reminders
  resources :vermifuges
  resources :vermifuge_reminders
  resources :vermifuges
  resources :vermifuge_reminders
  resources :appointment_reminders
  resources :appointments
  resources :owners
  resources :vaccines
  resources :vaccines
  resources :vaccines
  resources :weights
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'home/index'

  root 'home#index'

  resources :pets

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :pet
end

app/models/appointment_reminder.rb
class AppointmentReminder < ActiveRecord::Base
  belongs_to :appointment
end

app/models/bath.rb
class Bath < ActiveRecord::Base
end

app/models/bath_reminder.rb
class BathReminder < ActiveRecord::Base
  belongs_to :bath
end

app/models/owner.rb
class Owner < ActiveRecord::Base
end

app/models/pet.rb
class Pet < ActiveRecord::Base
  belongs_to :owner
end

app/models/vaccine.rb
class Vaccine < ActiveRecord::Base
  belongs_to :pet
end

app/models/vermifuge.rb
class Vermifuge < ActiveRecord::Base
end

app/models/vermifuge_reminder.rb
class VermifugeReminder < ActiveRecord::Base
  belongs_to :vermifuge
end

app/models/weight.rb
class Weight < ActiveRecord::Base
  belongs_to :pet
end

app/controllers/baths_controller.rb
class BathsController < ApplicationController
  before_action :set_bath, only: [:show, :edit, :update, :destroy]

  # GET /baths
  # GET /baths.json
  def index
    @baths = Bath.all
  end

  # GET /baths/1
  # GET /baths/1.json
  def show
  end

  # GET /baths/new
  def new
    @bath = Bath.new
  end

  # GET /baths/1/edit
  def edit
  end

  # POST /baths
  # POST /baths.json
  def create
    @bath = Bath.new(bath_params)

    respond_to do |format|
      if @bath.save
        format.html { redirect_to @bath, notice: 'Bath was successfully created.' }
        format.json { render :show, status: :created, location: @bath }
      else
        format.html { render :new }
        format.json { render json: @bath.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /baths/1
  # PATCH/PUT /baths/1.json
  def update
    respond_to do |format|
      if @bath.update(bath_params)
        format.html { redirect_to @bath, notice: 'Bath was successfully updated.' }
        format.json { render :show, status: :ok, location: @bath }
      else
        format.html { render :edit }
        format.json { render json: @bath.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /baths/1
  # DELETE /baths/1.json
  def destroy
    @bath.destroy
    respond_to do |format|
      format.html { redirect_to baths_url, notice: 'Bath was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bath
      @bath = Bath.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bath_params
      params.require(:bath).permit(:title, :date, :notes, :price)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:owner_id, :name, :birth, :sex, :specie, :breed, :color, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/baths_helper.rb
module BathsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/vaccines_helper.rb
module VaccinesHelper
end

app/helpers/vermifuges_helper.rb
module VermifugesHelper
end

app/helpers/weights_helper.rb
module WeightsHelper
end

app/views/baths/_form.html.erb
<%= form_for(@bath) do |f| %>
  <% if @bath.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bath.errors.count, "error") %> prohibited this bath from being saved:</h2>

      <ul>
      <% @bath.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/baths/edit.html.erb
<h1>Editing Bath</h1>

<%= render 'form' %>

<%= link_to 'Show', @bath %> |
<%= link_to 'Back', baths_path %>

app/views/baths/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Baths</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Date</th>
      <th>Notes</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @baths.each do |bath| %>
      <tr>
        <td><%= bath.title %></td>
        <td><%= bath.date %></td>
        <td><%= bath.notes %></td>
        <td><%= bath.price %></td>
        <td><%= link_to 'Show', bath %></td>
        <td><%= link_to 'Edit', edit_bath_path(bath) %></td>
        <td><%= link_to 'Destroy', bath, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bath', new_bath_path %>

app/views/baths/new.html.erb
<h1>New Bath</h1>

<%= render 'form' %>

<%= link_to 'Back', baths_path %>

app/views/baths/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @bath.title %>
</p>

<p>
  <strong>Date:</strong>
  <%= @bath.date %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @bath.notes %>
</p>

<p>
  <strong>Price:</strong>
  <%= @bath.price %>
</p>

<%= link_to 'Edit', edit_bath_path(@bath) %> |
<%= link_to 'Back', baths_path %>

app/views/pets/_form.html.erb
<%= form_for(@pet) do |f| %>
  <% if @pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% @pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :owner_id %><br>
    <%= f.text_field :owner_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :birth %><br>
    <%= f.date_select :birth %>
  </div>
  <div class="field">
    <%= f.label :sex %><br>
    <%= f.text_field :sex %>
  </div>
  <div class="field">
    <%= f.label :specie %><br>
    <%= f.text_field :specie %>
  </div>
  <div class="field">
    <%= f.label :breed %><br>
    <%= f.text_field :breed %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pets/edit.html.erb
<h1>Editing Pet</h1>

<%= render 'form' %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pets</h1>

<table>
  <thead>
    <tr>
      <th>Owner</th>
      <th>Name</th>
      <th>Birth</th>
      <th>Sex</th>
      <th>Specie</th>
      <th>Breed</th>
      <th>Color</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <td><%= pet.owner %></td>
        <td><%= pet.name %></td>
        <td><%= pet.birth %></td>
        <td><%= pet.sex %></td>
        <td><%= pet.specie %></td>
        <td><%= pet.breed %></td>
        <td><%= pet.color %></td>
        <td><%= pet.image %></td>
        <td><%= link_to 'Show', pet %></td>
        <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
        <td><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pet', new_pet_path %>

app/views/pets/new.html.erb
<h1>New Pet</h1>

<%= render 'form' %>

<%= link_to 'Back', pets_path %>

app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Owner:</strong>
  <%= @pet.owner %>
</p>

<p>
  <strong>Name:</strong>
  <%= @pet.name %>
</p>

<p>
  <strong>Birth:</strong>
  <%= @pet.birth %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @pet.sex %>
</p>

<p>
  <strong>Specie:</strong>
  <%= @pet.specie %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @pet.breed %>
</p>

<p>
  <strong>Color:</strong>
  <%= @pet.color %>
</p>

<p>
  <strong>Image:</strong>
  <%= @pet.image %>
</p>

<%= link_to 'Edit', edit_pet_path(@pet) %> |
<%= link_to 'Back', pets_path %>