config/routes.rb
Rails.application.routes.draw do
  resources :bath_reminders
  resources :baths
  resources :vermifuge_reminders
  resources :vermifuges
  resources :appointment_reminders
  resources :appointments
  resources :vaccines
  resources :weights
  resources :pets
  resources :owners
  resources :bath_reminders
  resources :baths
  resources :bath_reminders
  resources :baths
  resources :bath_reminders
  resources :baths
  resources :vermifuge_reminders
  resources :vermifuges
  resources :vermifuge_reminders
  resources :vermifuges
  resources :vermifuge_reminders
  resources :vermifuges
  resources :vermifuge_reminders
  resources :appointment_reminders
  resources :appointments
  resources :owners
  resources :vaccines
  resources :vaccines
  resources :vaccines
  resources :weights
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'home/index'

  root 'home#index'

  resources :pets

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :pet
end

app/models/appointment_reminder.rb
class AppointmentReminder < ActiveRecord::Base
  belongs_to :appointment
end

app/models/bath.rb
class Bath < ActiveRecord::Base
end

app/models/bath_reminder.rb
class BathReminder < ActiveRecord::Base
  belongs_to :bath
end

app/models/owner.rb
class Owner < ActiveRecord::Base
end

app/models/pet.rb
class Pet < ActiveRecord::Base
  belongs_to :owner
end

app/models/vaccine.rb
class Vaccine < ActiveRecord::Base
  belongs_to :pet
end

app/models/vermifuge.rb
class Vermifuge < ActiveRecord::Base
end

app/models/vermifuge_reminder.rb
class VermifugeReminder < ActiveRecord::Base
  belongs_to :vermifuge
end

app/models/weight.rb
class Weight < ActiveRecord::Base
  belongs_to :pet
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:owner_id, :name, :birth, :sex, :specie, :breed, :color, :image)
    end
end

app/controllers/vaccines_controller.rb
class VaccinesController < ApplicationController
  before_action :set_vaccine, only: [:show, :edit, :update, :destroy]

  # GET /vaccines
  # GET /vaccines.json
  def index
    @vaccines = Vaccine.all
  end

  # GET /vaccines/1
  # GET /vaccines/1.json
  def show
  end

  # GET /vaccines/new
  def new
    @vaccine = Vaccine.new
  end

  # GET /vaccines/1/edit
  def edit
  end

  # POST /vaccines
  # POST /vaccines.json
  def create
    @vaccine = Vaccine.new(vaccine_params)

    respond_to do |format|
      if @vaccine.save
        format.html { redirect_to @vaccine, notice: 'Vaccine was successfully created.' }
        format.json { render :show, status: :created, location: @vaccine }
      else
        format.html { render :new }
        format.json { render json: @vaccine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vaccines/1
  # PATCH/PUT /vaccines/1.json
  def update
    respond_to do |format|
      if @vaccine.update(vaccine_params)
        format.html { redirect_to @vaccine, notice: 'Vaccine was successfully updated.' }
        format.json { render :show, status: :ok, location: @vaccine }
      else
        format.html { render :edit }
        format.json { render json: @vaccine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vaccines/1
  # DELETE /vaccines/1.json
  def destroy
    @vaccine.destroy
    respond_to do |format|
      format.html { redirect_to vaccines_url, notice: 'Vaccine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vaccine
      @vaccine = Vaccine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vaccine_params
      params.require(:vaccine).permit(:pet_id, :veterinary_name, :parent_vaccine, :notes, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/baths_helper.rb
module BathsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/vaccines_helper.rb
module VaccinesHelper
end

app/helpers/vermifuges_helper.rb
module VermifugesHelper
end

app/helpers/weights_helper.rb
module WeightsHelper
end

app/views/vaccines/_form.html.erb
<%= form_for(@vaccine) do |f| %>
  <% if @vaccine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vaccine.errors.count, "error") %> prohibited this vaccine from being saved:</h2>

      <ul>
      <% @vaccine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pet_id %><br>
    <%= f.text_field :pet_id %>
  </div>
  <div class="field">
    <%= f.label :veterinary_name %><br>
    <%= f.text_field :veterinary_name %>
  </div>
  <div class="field">
    <%= f.label :parent_vaccine %><br>
    <%= f.number_field :parent_vaccine %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vaccines/edit.html.erb
<h1>Editing Vaccine</h1>

<%= render 'form' %>

<%= link_to 'Show', @vaccine %> |
<%= link_to 'Back', vaccines_path %>

app/views/vaccines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Vaccines</h1>

<table>
  <thead>
    <tr>
      <th>Pet</th>
      <th>Veterinary name</th>
      <th>Parent vaccine</th>
      <th>Notes</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vaccines.each do |vaccine| %>
      <tr>
        <td><%= vaccine.pet %></td>
        <td><%= vaccine.veterinary_name %></td>
        <td><%= vaccine.parent_vaccine %></td>
        <td><%= vaccine.notes %></td>
        <td><%= vaccine.date %></td>
        <td><%= link_to 'Show', vaccine %></td>
        <td><%= link_to 'Edit', edit_vaccine_path(vaccine) %></td>
        <td><%= link_to 'Destroy', vaccine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vaccine', new_vaccine_path %>

app/views/vaccines/new.html.erb
<h1>New Vaccine</h1>

<%= render 'form' %>

<%= link_to 'Back', vaccines_path %>

app/views/vaccines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pet:</strong>
  <%= @vaccine.pet %>
</p>

<p>
  <strong>Veterinary name:</strong>
  <%= @vaccine.veterinary_name %>
</p>

<p>
  <strong>Parent vaccine:</strong>
  <%= @vaccine.parent_vaccine %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @vaccine.notes %>
</p>

<p>
  <strong>Date:</strong>
  <%= @vaccine.date %>
</p>

<%= link_to 'Edit', edit_vaccine_path(@vaccine) %> |
<%= link_to 'Back', vaccines_path %>